[unstable]
{% if std %}
build-std = ["std", "panic_abort"]{% else %}build-std = ["core", "alloc", "panic_abort"]{% endif %}
# Required for older ESP-IDF versions without a realpath implementation.
# Enabling panic_immediate_abort may remove 100K+ from binary size but panic messages will not be printed.
{% if espidfver != "v4.3.2" %}#{% endif %}build-std-features = ["panic_immediate_abort"]
